<?php
/*=========================================================================
 Midas Server
 Copyright Kitware SAS, 26 rue Louis Guérin, 69100 Villeurbanne, France.
 All rights reserved.
 For more information visit http://www.kitware.com/.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0.txt

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
=========================================================================*/

?>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>

<div class="loginPage">
<h3>Welcome to the RSNA QIDW. Please Login</h3>

<form id="rsnaLoginForm" method="<?php echo $this->form['method'] ?>" method='POST' action="<?php echo $this->form['action'] ?>">
    <input type="hidden" name="previousuri" value=""/>
    <table>
        <tr>
            <td><label for="email"><?php echo $this->t('Email') ?></label></td>
            <td>
                <label for="password"><?php echo $this->t('Password') ?></label>
                <?php
                if ($this->allowPasswordReset) {
                    ?>
                    <a id='forgotPasswordLink' style='text-decoration: underline;font-size: 10px;'
                       href="#"><?php echo $this->t('Forgot your password'); ?>?</a>
                    <?php
                }
                ?>
            </td>
            <td></td>
        </tr>
        <tr>
            <td id="rsnaEmail"><?php echo $this->form['email'] ?></td>
            <td id="rsnaPassword"><?php echo $this->form['password'] ?></td>
            <td></td>
        </tr>
        <tr>
            <td>
                <?php
                if (!$this->closeRegistration) { ?>
                    Not registered yet? <a class="rsnaRegisterLink" href="<?php echo $this->moduleWebroot.'/auth/register'; ?>">Register here</a>
                    <?php
                }
                ?>
            </td>
            <td><?php echo $this->form['remerberMe'] ?>
                <label id="rememberMeText" for="remerberMe"><?php echo $this->t("Remember Me") ?></label></td>
            <td></td>
        </tr>
        <tr>
            <td>
                <?php echo $this->form['submit'] ?>
                <img style="display: none;" alt=""
                     src="<?php echo $this->coreWebroot; ?>/public/images/icons/loading.gif" id="loginWaiting"/>
            </td>
            <td></td>
            <td></td>
        </tr>
    </table>
</form>

</div>
<?php
$this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jquery.form.js');
$this->headScript()->appendFile($this->moduleWebroot.'/public/js/login.js');
?>